# Generated by Django 3.2.19 on 2026-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Paste YouTube embed URL: https://www.youtube.com/embed/VIDEO_ID', null=True),
        ),
    ]
