# Generated by Django 3.2.19 on 2026-04-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260425_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='screen_type',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX 3D')], default='2D', max_length=10),
        ),
    ]
