# Generated by Django 3.2.19 on 2026-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20260427_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_booked__10b11b_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_movie_i_323598_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_theater_a2fd03_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='locked_by',
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('sci_fi', 'Sci-Fi'), ('animation', 'Animation'), ('biography', 'Biography'), ('fantasy', 'Fantasy')], db_index=True, default='action', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('english', 'English'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('punjabi', 'Punjabi'), ('bengali', 'Bengali')], db_index=True, default='hindi', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theater',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'language'], name='movie_genre_lang_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre', 'rating'], name='movie_genre_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'rating'], name='movie_lang_rating_idx'),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
