# Generated by Django 3.2.19 on 2026-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20260427_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at', 'payment_status'], name='movies_book_booked__10b11b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'booked_at'], name='movies_book_movie_i_323598_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'booked_at'], name='movies_book_theater_a2fd03_idx'),
        ),
    ]
